swagger: '2.0'
info:
  title: Jouko API
  description: Jouko API spec
  version: "0.0.1"
schemes:
  - https
basePath: /v1
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - bearer: []
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /users/{userid}/interruptions:
    get:
      operationId: listInterruptions
      summary: List interruptions
      parameters:
        - name: userid
          in: path
          description: The user whose interruptions we list
          required: true
          type: integer
        - name: from
          in: query
          description: List interruptions that start after this point of time, inclusive
          required: true
          type: string
          format: date-time
        - name: to
          in: query
          description: List interruptions that end before this point of time, exclusive
          required: true
          type: string
          format: date-time
      responses:
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Interruption'
  /users/{userid}/interruptions/{interruptionid}/cancelled:
    put:
      operationId: setInterruptionCancelled
      summary: "Set interruption's cancellation status"
      parameters:
        - name: userid
          in: path
          description: The user who owns the interruption
          required: true
          type: integer
        - name: interruptionid
          in: path
          description: The id of the interruption to set cancellation status of
          required: true
          type: integer
        - name: body
          in: body
          description: The cancellation status
          required: true
          schema:
            $ref: '#/definitions/InterruptionCancellation'
      responses:
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
        200:
          description: Success
          schema:
            $ref: '#/definitions/InterruptionCancellation'
  /users/{userid}/devices:
    get:
      operationId: listDevices
      summary: List devices
      parameters:
        - name: userid
          in: path
          description: The user who owns the interruption
          required: true
          type: integer
        - name: firstResult
          in: query
          description: "The offset of the first result"
          required: true
          type: integer
        - name: maxResults
          in: query
          description: "The maximum number of results"
          required: true
          type: integer
      responses:
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
  /users/{userid}/devices/{deviceid}/powerConsumption:
    get:
      operationId: getPowerConsumption
      summary: Get the power consumption of the given device in a time period
      parameters:
        - name: userid
          in: path
          description: The user that owns the device
          required: true
          type: integer
        - name: userid
          in: path
          description: The device whose power consumption we measure
          required: true
          type: integer
        - name: from
          in: query
          description: The start of the time period that we measure the consumption in, inclusive
          required: true
          type: string
          format: date-time
        - name: to
          in: query
          description: The end of the time period that we measure the consumption in, exclusive
          required: true
          type: string
          format: date-time
      responses:
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/DevicePowerConsumption'
definitions:
  Unauthorized:
    type: object
    properties:
      message:
        description: The error message
        type: string
  InternalServerError:
    type: object
    properties:
      message:
        description: The error message
        type: string
  Interruption:
    type: object
    properties:
      id:
        description: Interruption id
        type: string
        format: uuid
      from:
        description: Start time of the interruption, inclusive
        type: string
        format: date-time
      to:
        description: End time of the interruption, exclusive
        type: string
        format: date-time
      deviceId:
        description: The ID of the interrupted device
        type: string
        format: uuid
      cancelled:
        description: True if the interruption has been cancelled
        type: boolean
  InterruptionCancellation:
    type: object
    properties:
      cancelled:
        description: True if the interruption has been cancelled
        type: boolean
  Device:
    type: object
    properties:
      id:
        description: Interruption id
        type: string
        format: uuid
      name:
        description: The name of the device
        type: string
  DevicePowerConsumption:
    type: object
    properties:
      consumptionInWatts:
        description: The power consumption in the given time span, in watts
        type: number
      