swagger: '2.0'
info:
  title: Jouko API
  description: Jouko API spec
  version: 0.0.4
schemes:
  - https
basePath: /v1
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - bearer: []
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  '/admin/interruptiongroups/':
    get:
      operationId: listInterruptionGroups
      tags:
        - Interruption Groups
      summary: List interruption groups
      parameters:
        - name: firstResult
          in: query
          description: The offset of the first result
          required: true
          type: integer
        - name: maxResults
          in: query
          description: The maximum number of results
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/InterruptionGroup'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    post:
      operationId: createInterruptionGroup
      tags:
        - Interruption Groups
      summary: Create interruption group
      parameters:
        - name: body
          in: body
          description: The cancellation status
          required: true
          schema:
            $ref: '#/definitions/InterruptionGroup'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/InterruptionGroup'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/admin/interruptiongroups/{groupId}':
    get:
      operationId: retrieveInterruptionGroup
      tags:
        - Interruptions
      summary: Retreive interruption group
      parameters:
        - name: groupId
          in: path
          description: The id of the interruption group
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/InterruptionGroup'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateInterruptionGroup
      tags:
        - Interruptions
      summary: Update interruption group
      parameters:
        - name: groupId
          in: path
          description: The id of the interruption group
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          description: The cancellation status
          required: true
          schema:
            $ref: '#/definitions/InterruptionGroup'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/InterruptionGroup'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/keycloakUsers/{keycloakId}':
    get:
      operationId: getUserByKeycloakId
      tags:
        - Users
      summary: Get an user by keycloak id
      parameters:
        - name: keycloakId
          in: path
          description: The keycloak id of the user to look up
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/users/{userId}/interruptions':
    get:
      operationId: listInterruptions
      tags:
        - Interruptions
      summary: List interruptions
      parameters:
        - name: userId
          in: path
          description: The user whose interruptions we list
          required: true
          type: integer
          format: int64
        - name: fromTime
          in: query
          description: List interruptions that start after this point of time, inclusive
          required: true
          type: string
          format: date-time
        - name: toTime
          in: query
          description: List interruptions that end before this point of time, exclusive
          required: true
          type: string
          format: date-time
        - name: deviceId
          in: query
          description: The device id whose interruptions we list, list all if omitted
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Interruption'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/users/{userId}/interruptions/{interruptionId}/cancelled':
    put:
      operationId: setInterruptionCancelled
      tags:
        - Interruptions
      summary: Set interruption's cancellation status
      parameters:
        - name: userId
          in: path
          description: The user who owns the interruption
          required: true
          type: integer
          format: int64
        - name: interruptionId
          in: path
          description: The id of the interruption to set cancellation status of
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          description: The cancellation status
          required: true
          schema:
            $ref: '#/definitions/InterruptionCancellation'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/InterruptionCancellation'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/users/{userId}/devices':
    get:
      operationId: listDevices
      tags:
        - Devices
      summary: List devices
      parameters:
        - name: userId
          in: path
          description: The user who owns the interruption
          required: true
          type: integer
          format: int64
        - name: firstResult
          in: query
          description: The offset of the first result
          required: true
          type: integer
        - name: maxResults
          in: query
          description: The maximum number of results
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/users/{userId}/devices/{deviceId}/powerConsumption':
    get:
      operationId: getPowerConsumption
      tags:
        - Devices
      summary: Get the power consumption of the given device in a time period
      parameters:
        - name: userId
          in: path
          description: The user that owns the device
          required: true
          type: integer
          format: int64
        - name: deviceId
          in: path
          description: The device whose power consumption we measure
          required: true
          type: integer
          format: int64
        - name: fromTime
          in: query
          description: >-
            The start of the time period that we measure the consumption in,
            inclusive
          required: true
          type: string
          format: date-time
        - name: toTime
          in: query
          description: >-
            The end of the time period that we measure the consumption in,
            exclusive
          required: true
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DevicePowerConsumption'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
definitions:
  Unauthorized:
    type: object
    required: [message]
    properties:
      message:
        description: The error message
        type: string
  InternalServerError:
    type: object
    required: [message]
    properties:
      message:
        description: The error message
        type: string
  User:
    type: object
    required:
      - id
      - name
      - keycloakId
    properties:
      id:
        description: User id
        type: integer
        format: int64
      name:
        description: The name of the user
        type: string
      keycloakId:
        description: The keycloak id of the user
        type: string
        format: uuid
  InterruptionGroup:
    type: object
    required:
      - id
      - startTime
      - endTime
    properties:
      id:
        description: Interruption id
        type: integer
        format: int64
      startTime:
        description: 'Start time of the interruption, inclusive'
        type: string
        format: date-time
      endTime:
        description: 'End time of the interruption, exclusive'
        type: string
        format: date-time
  Interruption:
    type: object
    required:
      - id
      - startTime
      - endTime
      - deviceId
      - cancelled
    properties:
      id:
        description: Interruption id
        type: integer
        format: int64
      startTime:
        description: 'Start time of the interruption, inclusive'
        type: string
        format: date-time
      endTime:
        description: 'End time of the interruption, exclusive'
        type: string
        format: date-time
      deviceId:
        description: The ID of the interrupted device
        type: integer
        format: int64
      cancelled:
        description: True if the interruption has been cancelled
        type: boolean
      cancellationTime:
        description: The time when the interruption was cancelled
        type: string
        format: date-time
  InterruptionCancellation:
    type: object
    required: [cancelled]
    properties:
      cancelled:
        description: True if the interruption has been cancelled
        type: boolean
  Device:
    type: object
    required:
      - id
      - name
    properties:
      id:
        description: Device id
        type: integer
        format: int64
      name:
        description: The name of the device
        type: string
  DevicePowerConsumption:
    type: object
    required: [averageConsumptionInWatts]
    properties:
      averageConsumptionInWatts:
        description: 'The power consumption in the given time span, in watts'
        type: number
        format: double
