swagger: '2.0'
info:
  title: Jouko API
  description: Jouko API spec
  version: "0.0.1"
schemes:
  - https
basePath: /v1
securityDefinitions:
  basicAuth:
    type: basic
security:
- basicAuth: []
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
definitions:
