// tslint:disable
/**
 * Jouko API
 * Jouko API spec
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost/v1".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<any>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * Device id
     * @type {number}
     * @memberof Device
     */
    id: number;
    /**
     * The name of the device
     * @type {string}
     * @memberof Device
     */
    name: string;
}

/**
 * 
 * @export
 * @interface DevicePowerConsumption
 */
export interface DevicePowerConsumption {
    /**
     * The power consumption in the given time span, in watts
     * @type {number}
     * @memberof DevicePowerConsumption
     */
    averageConsumptionInWatts: number;
}

/**
 * 
 * @export
 * @interface InternalServerError
 */
export interface InternalServerError {
    /**
     * The error message
     * @type {string}
     * @memberof InternalServerError
     */
    message: string;
}

/**
 * 
 * @export
 * @interface Interruption
 */
export interface Interruption {
    /**
     * Interruption id
     * @type {number}
     * @memberof Interruption
     */
    id: number;
    /**
     * Start time of the interruption, inclusive
     * @type {string}
     * @memberof Interruption
     */
    startTime: string;
    /**
     * End time of the interruption, exclusive
     * @type {string}
     * @memberof Interruption
     */
    endTime: string;
    /**
     * The ID of the interrupted device
     * @type {number}
     * @memberof Interruption
     */
    deviceId: number;
    /**
     * True if the interruption has been cancelled
     * @type {boolean}
     * @memberof Interruption
     */
    cancelled: boolean;
    /**
     * The time when the interruption was cancelled
     * @type {string}
     * @memberof Interruption
     */
    cancellationTime?: string;
}

/**
 * 
 * @export
 * @interface InterruptionCancellation
 */
export interface InterruptionCancellation {
    /**
     * True if the interruption has been cancelled
     * @type {boolean}
     * @memberof InterruptionCancellation
     */
    cancelled: boolean;
}

/**
 * 
 * @export
 * @interface InterruptionGroup
 */
export interface InterruptionGroup {
    /**
     * Interruption id
     * @type {number}
     * @memberof InterruptionGroup
     */
    id: number;
    /**
     * Start time of the interruption, inclusive
     * @type {string}
     * @memberof InterruptionGroup
     */
    startTime: string;
    /**
     * End time of the interruption, exclusive
     * @type {string}
     * @memberof InterruptionGroup
     */
    endTime: string;
}

/**
 * 
 * @export
 * @interface Unauthorized
 */
export interface Unauthorized {
    /**
     * The error message
     * @type {string}
     * @memberof Unauthorized
     */
    message: string;
}

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * User id
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * The name of the user
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * The keycloak id of the user
     * @type {string}
     * @memberof User
     */
    keycloakId: string;
}


/**
 * DevicesApi - fetch parameter creator
 * @export
 */
export const DevicesApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the power consumption of the given device in a time period
         * @param {number} userId The user that owns the device
         * @param {number} deviceId The device whose power consumption we measure
         * @param {string} fromTime The start of the time period that we measure the consumption in, inclusive
         * @param {string} toTime The end of the time period that we measure the consumption in, exclusive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPowerConsumption(userId: number, deviceId: number, fromTime: string, toTime: string, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling getPowerConsumption.');
            }
            // verify required parameter 'deviceId' is not null or undefined
            if (deviceId === null || deviceId === undefined) {
                throw new RequiredError('deviceId','Required parameter deviceId was null or undefined when calling getPowerConsumption.');
            }
            // verify required parameter 'fromTime' is not null or undefined
            if (fromTime === null || fromTime === undefined) {
                throw new RequiredError('fromTime','Required parameter fromTime was null or undefined when calling getPowerConsumption.');
            }
            // verify required parameter 'toTime' is not null or undefined
            if (toTime === null || toTime === undefined) {
                throw new RequiredError('toTime','Required parameter toTime was null or undefined when calling getPowerConsumption.');
            }
            const path = `/users/{userId}/devices/{deviceId}/powerConsumption`
                .replace(`{${"userId"}}`, String(userId))
                .replace(`{${"deviceId"}}`, String(deviceId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            if (fromTime !== undefined) {
                queryParameter['fromTime'] = fromTime;
            }

            if (toTime !== undefined) {
                queryParameter['toTime'] = toTime;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @summary List devices
         * @param {number} userId The user who owns the interruption
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(userId: number, firstResult: number, maxResults: number, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling listDevices.');
            }
            // verify required parameter 'firstResult' is not null or undefined
            if (firstResult === null || firstResult === undefined) {
                throw new RequiredError('firstResult','Required parameter firstResult was null or undefined when calling listDevices.');
            }
            // verify required parameter 'maxResults' is not null or undefined
            if (maxResults === null || maxResults === undefined) {
                throw new RequiredError('maxResults','Required parameter maxResults was null or undefined when calling listDevices.');
            }
            const path = `/users/{userId}/devices`
                .replace(`{${"userId"}}`, String(userId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            if (firstResult !== undefined) {
                queryParameter['firstResult'] = firstResult;
            }

            if (maxResults !== undefined) {
                queryParameter['maxResults'] = maxResults;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
    }
};

/**
 * DevicesApi - functional programming interface
 * @export
 */
export const DevicesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the power consumption of the given device in a time period
         * @param {number} userId The user that owns the device
         * @param {number} deviceId The device whose power consumption we measure
         * @param {string} fromTime The start of the time period that we measure the consumption in, inclusive
         * @param {string} toTime The end of the time period that we measure the consumption in, exclusive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPowerConsumption(userId: number, deviceId: number, fromTime: string, toTime: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DevicePowerConsumption> {
            const fetchArgs = DevicesApiFetchParamCreator(configuration).getPowerConsumption(userId, deviceId, fromTime, toTime, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary List devices
         * @param {number} userId The user who owns the interruption
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(userId: number, firstResult: number, maxResults: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Device>> {
            const fetchArgs = DevicesApiFetchParamCreator(configuration).listDevices(userId, firstResult, maxResults, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DevicesApi - factory interface
 * @export
 */
export const DevicesApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Get the power consumption of the given device in a time period
         * @param {number} userId The user that owns the device
         * @param {number} deviceId The device whose power consumption we measure
         * @param {string} fromTime The start of the time period that we measure the consumption in, inclusive
         * @param {string} toTime The end of the time period that we measure the consumption in, exclusive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPowerConsumption(userId: number, deviceId: number, fromTime: string, toTime: string, options?: any) {
            return DevicesApiFp(configuration).getPowerConsumption(userId, deviceId, fromTime, toTime, options)(fetch, basePath);
        },
        /**
         * 
         * @summary List devices
         * @param {number} userId The user who owns the interruption
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(userId: number, firstResult: number, maxResults: number, options?: any) {
            return DevicesApiFp(configuration).listDevices(userId, firstResult, maxResults, options)(fetch, basePath);
        },
    };
};

/**
 * DevicesApi - object-oriented interface
 * @export
 * @class DevicesApi
 * @extends {BaseAPI}
 */
export class DevicesApi extends BaseAPI {
    /**
     * 
     * @summary Get the power consumption of the given device in a time period
     * @param {} userId The user that owns the device
     * @param {} deviceId The device whose power consumption we measure
     * @param {} fromTime The start of the time period that we measure the consumption in, inclusive
     * @param {} toTime The end of the time period that we measure the consumption in, exclusive
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public getPowerConsumption(userId: number, deviceId: number, fromTime: string, toTime: string, options?: any) {
        return DevicesApiFp(this.configuration).getPowerConsumption(userId, deviceId, fromTime, toTime, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary List devices
     * @param {} userId The user who owns the interruption
     * @param {} firstResult The offset of the first result
     * @param {} maxResults The maximum number of results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public listDevices(userId: number, firstResult: number, maxResults: number, options?: any) {
        return DevicesApiFp(this.configuration).listDevices(userId, firstResult, maxResults, options)(this.fetch, this.basePath);
    }

}

/**
 * InterruptionGroupsApi - fetch parameter creator
 * @export
 */
export const InterruptionGroupsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInterruptionGroup(body: InterruptionGroup, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createInterruptionGroup.');
            }
            const path = `/admin/interruptiongroups/`;
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'POST' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            headerParameter['Content-Type'] = 'application/json';

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);
            requestOptions.body = JSON.stringify(body || {});

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @summary List interruption groups
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptionGroups(firstResult: number, maxResults: number, options: any = {}): FetchArgs {
            // verify required parameter 'firstResult' is not null or undefined
            if (firstResult === null || firstResult === undefined) {
                throw new RequiredError('firstResult','Required parameter firstResult was null or undefined when calling listInterruptionGroups.');
            }
            // verify required parameter 'maxResults' is not null or undefined
            if (maxResults === null || maxResults === undefined) {
                throw new RequiredError('maxResults','Required parameter maxResults was null or undefined when calling listInterruptionGroups.');
            }
            const path = `/admin/interruptiongroups/`;
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            if (firstResult !== undefined) {
                queryParameter['firstResult'] = firstResult;
            }

            if (maxResults !== undefined) {
                queryParameter['maxResults'] = maxResults;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
    }
};

/**
 * InterruptionGroupsApi - functional programming interface
 * @export
 */
export const InterruptionGroupsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInterruptionGroup(body: InterruptionGroup, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InterruptionGroup> {
            const fetchArgs = InterruptionGroupsApiFetchParamCreator(configuration).createInterruptionGroup(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary List interruption groups
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptionGroups(firstResult: number, maxResults: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<InterruptionGroup>> {
            const fetchArgs = InterruptionGroupsApiFetchParamCreator(configuration).listInterruptionGroups(firstResult, maxResults, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * InterruptionGroupsApi - factory interface
 * @export
 */
export const InterruptionGroupsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Create interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInterruptionGroup(body: InterruptionGroup, options?: any) {
            return InterruptionGroupsApiFp(configuration).createInterruptionGroup(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary List interruption groups
         * @param {number} firstResult The offset of the first result
         * @param {number} maxResults The maximum number of results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptionGroups(firstResult: number, maxResults: number, options?: any) {
            return InterruptionGroupsApiFp(configuration).listInterruptionGroups(firstResult, maxResults, options)(fetch, basePath);
        },
    };
};

/**
 * InterruptionGroupsApi - object-oriented interface
 * @export
 * @class InterruptionGroupsApi
 * @extends {BaseAPI}
 */
export class InterruptionGroupsApi extends BaseAPI {
    /**
     * 
     * @summary Create interruption group
     * @param {} body The cancellation status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionGroupsApi
     */
    public createInterruptionGroup(body: InterruptionGroup, options?: any) {
        return InterruptionGroupsApiFp(this.configuration).createInterruptionGroup(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary List interruption groups
     * @param {} firstResult The offset of the first result
     * @param {} maxResults The maximum number of results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionGroupsApi
     */
    public listInterruptionGroups(firstResult: number, maxResults: number, options?: any) {
        return InterruptionGroupsApiFp(this.configuration).listInterruptionGroups(firstResult, maxResults, options)(this.fetch, this.basePath);
    }

}

/**
 * InterruptionsApi - fetch parameter creator
 * @export
 */
export const InterruptionsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List interruptions
         * @param {number} userId The user whose interruptions we list
         * @param {string} fromTime List interruptions that start after this point of time, inclusive
         * @param {string} toTime List interruptions that end before this point of time, exclusive
         * @param {number} [deviceId] The device id whose interruptions we list, list all if omitted
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptions(userId: number, fromTime: string, toTime: string, deviceId?: number, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling listInterruptions.');
            }
            // verify required parameter 'fromTime' is not null or undefined
            if (fromTime === null || fromTime === undefined) {
                throw new RequiredError('fromTime','Required parameter fromTime was null or undefined when calling listInterruptions.');
            }
            // verify required parameter 'toTime' is not null or undefined
            if (toTime === null || toTime === undefined) {
                throw new RequiredError('toTime','Required parameter toTime was null or undefined when calling listInterruptions.');
            }
            const path = `/users/{userId}/interruptions`
                .replace(`{${"userId"}}`, String(userId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            if (fromTime !== undefined) {
                queryParameter['fromTime'] = fromTime;
            }

            if (toTime !== undefined) {
                queryParameter['toTime'] = toTime;
            }

            if (deviceId !== undefined) {
                queryParameter['deviceId'] = deviceId;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @summary Retreive interruption group
         * @param {number} groupId The id of the interruption group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveInterruptionGroup(groupId: number, options: any = {}): FetchArgs {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling retrieveInterruptionGroup.');
            }
            const path = `/admin/interruptiongroups/{groupId}`
                .replace(`{${"groupId"}}`, String(groupId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @summary Set interruption's cancellation status
         * @param {number} userId The user who owns the interruption
         * @param {number} interruptionId The id of the interruption to set cancellation status of
         * @param {InterruptionCancellation} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setInterruptionCancelled(userId: number, interruptionId: number, body: InterruptionCancellation, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling setInterruptionCancelled.');
            }
            // verify required parameter 'interruptionId' is not null or undefined
            if (interruptionId === null || interruptionId === undefined) {
                throw new RequiredError('interruptionId','Required parameter interruptionId was null or undefined when calling setInterruptionCancelled.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling setInterruptionCancelled.');
            }
            const path = `/users/{userId}/interruptions/{interruptionId}/cancelled`
                .replace(`{${"userId"}}`, String(userId))
                .replace(`{${"interruptionId"}}`, String(interruptionId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'PUT' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            headerParameter['Content-Type'] = 'application/json';

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);
            requestOptions.body = JSON.stringify(body || {});

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @summary Update interruption group
         * @param {number} groupId The id of the interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInterruptionGroup(groupId: number, body: InterruptionGroup, options: any = {}): FetchArgs {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling updateInterruptionGroup.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateInterruptionGroup.');
            }
            const path = `/admin/interruptiongroups/{groupId}`
                .replace(`{${"groupId"}}`, String(groupId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'PUT' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            headerParameter['Content-Type'] = 'application/json';

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);
            requestOptions.body = JSON.stringify(body || {});

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
    }
};

/**
 * InterruptionsApi - functional programming interface
 * @export
 */
export const InterruptionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List interruptions
         * @param {number} userId The user whose interruptions we list
         * @param {string} fromTime List interruptions that start after this point of time, inclusive
         * @param {string} toTime List interruptions that end before this point of time, exclusive
         * @param {number} [deviceId] The device id whose interruptions we list, list all if omitted
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptions(userId: number, fromTime: string, toTime: string, deviceId?: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Interruption>> {
            const fetchArgs = InterruptionsApiFetchParamCreator(configuration).listInterruptions(userId, fromTime, toTime, deviceId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Retreive interruption group
         * @param {number} groupId The id of the interruption group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveInterruptionGroup(groupId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InterruptionGroup> {
            const fetchArgs = InterruptionsApiFetchParamCreator(configuration).retrieveInterruptionGroup(groupId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Set interruption's cancellation status
         * @param {number} userId The user who owns the interruption
         * @param {number} interruptionId The id of the interruption to set cancellation status of
         * @param {InterruptionCancellation} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setInterruptionCancelled(userId: number, interruptionId: number, body: InterruptionCancellation, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InterruptionCancellation> {
            const fetchArgs = InterruptionsApiFetchParamCreator(configuration).setInterruptionCancelled(userId, interruptionId, body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update interruption group
         * @param {number} groupId The id of the interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInterruptionGroup(groupId: number, body: InterruptionGroup, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InterruptionGroup> {
            const fetchArgs = InterruptionsApiFetchParamCreator(configuration).updateInterruptionGroup(groupId, body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * InterruptionsApi - factory interface
 * @export
 */
export const InterruptionsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary List interruptions
         * @param {number} userId The user whose interruptions we list
         * @param {string} fromTime List interruptions that start after this point of time, inclusive
         * @param {string} toTime List interruptions that end before this point of time, exclusive
         * @param {number} [deviceId] The device id whose interruptions we list, list all if omitted
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInterruptions(userId: number, fromTime: string, toTime: string, deviceId?: number, options?: any) {
            return InterruptionsApiFp(configuration).listInterruptions(userId, fromTime, toTime, deviceId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Retreive interruption group
         * @param {number} groupId The id of the interruption group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveInterruptionGroup(groupId: number, options?: any) {
            return InterruptionsApiFp(configuration).retrieveInterruptionGroup(groupId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Set interruption's cancellation status
         * @param {number} userId The user who owns the interruption
         * @param {number} interruptionId The id of the interruption to set cancellation status of
         * @param {InterruptionCancellation} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setInterruptionCancelled(userId: number, interruptionId: number, body: InterruptionCancellation, options?: any) {
            return InterruptionsApiFp(configuration).setInterruptionCancelled(userId, interruptionId, body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update interruption group
         * @param {number} groupId The id of the interruption group
         * @param {InterruptionGroup} body The cancellation status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInterruptionGroup(groupId: number, body: InterruptionGroup, options?: any) {
            return InterruptionsApiFp(configuration).updateInterruptionGroup(groupId, body, options)(fetch, basePath);
        },
    };
};

/**
 * InterruptionsApi - object-oriented interface
 * @export
 * @class InterruptionsApi
 * @extends {BaseAPI}
 */
export class InterruptionsApi extends BaseAPI {
    /**
     * 
     * @summary List interruptions
     * @param {} userId The user whose interruptions we list
     * @param {} fromTime List interruptions that start after this point of time, inclusive
     * @param {} toTime List interruptions that end before this point of time, exclusive
     * @param {} [deviceId] The device id whose interruptions we list, list all if omitted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionsApi
     */
    public listInterruptions(userId: number, fromTime: string, toTime: string, deviceId?: number, options?: any) {
        return InterruptionsApiFp(this.configuration).listInterruptions(userId, fromTime, toTime, deviceId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Retreive interruption group
     * @param {} groupId The id of the interruption group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionsApi
     */
    public retrieveInterruptionGroup(groupId: number, options?: any) {
        return InterruptionsApiFp(this.configuration).retrieveInterruptionGroup(groupId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Set interruption's cancellation status
     * @param {} userId The user who owns the interruption
     * @param {} interruptionId The id of the interruption to set cancellation status of
     * @param {} body The cancellation status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionsApi
     */
    public setInterruptionCancelled(userId: number, interruptionId: number, body: InterruptionCancellation, options?: any) {
        return InterruptionsApiFp(this.configuration).setInterruptionCancelled(userId, interruptionId, body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update interruption group
     * @param {} groupId The id of the interruption group
     * @param {} body The cancellation status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterruptionsApi
     */
    public updateInterruptionGroup(groupId: number, body: InterruptionGroup, options?: any) {
        return InterruptionsApiFp(this.configuration).updateInterruptionGroup(groupId, body, options)(this.fetch, this.basePath);
    }

}

/**
 * UsersApi - fetch parameter creator
 * @export
 */
export const UsersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get an user by keycloak id
         * @param {string} keycloakId The keycloak id of the user to look up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByKeycloakId(keycloakId: string, options: any = {}): FetchArgs {
            // verify required parameter 'keycloakId' is not null or undefined
            if (keycloakId === null || keycloakId === undefined) {
                throw new RequiredError('keycloakId','Required parameter keycloakId was null or undefined when calling getUserByKeycloakId.');
            }
            const path = `/keycloakUsers/{keycloakId}`
                .replace(`{${"keycloakId"}}`, String(keycloakId));
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            // authentication bearer required
            if (configuration && configuration.apiKey) {
                const apiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                headerParameter["Authorization"] = apiKeyValue;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get an user by keycloak id
         * @param {string} keycloakId The keycloak id of the user to look up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByKeycloakId(keycloakId: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<User> {
            const fetchArgs = UsersApiFetchParamCreator(configuration).getUserByKeycloakId(keycloakId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Get an user by keycloak id
         * @param {string} keycloakId The keycloak id of the user to look up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByKeycloakId(keycloakId: string, options?: any) {
            return UsersApiFp(configuration).getUserByKeycloakId(keycloakId, options)(fetch, basePath);
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Get an user by keycloak id
     * @param {} keycloakId The keycloak id of the user to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserByKeycloakId(keycloakId: string, options?: any) {
        return UsersApiFp(this.configuration).getUserByKeycloakId(keycloakId, options)(this.fetch, this.basePath);
    }

}

